"""Add name and created_at to User

Revision ID: 189f1d76867d
Revises: e1f5eabbc4f9
Create Date: 2025-07-10 07:23:09.983167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189f1d76867d'
down_revision = 'e1f5eabbc4f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('created_at')
        batch_op.drop_column('username')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
