"""Stock models

Revision ID: 44262f9878a0
Revises: 39ed17d91ae8
Create Date: 2025-06-30 07:50:24.594518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44262f9878a0'
down_revision = '39ed17d91ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('company_email', sa.String(length=100), nullable=False),
    sa.Column('company_phone', sa.String(length=20), nullable=False),
    sa.Column('company_phone_2', sa.String(length=20), nullable=True),
    sa.Column('county', sa.String(length=50), nullable=False),
    sa.Column('sub_county', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('company_address', sa.String(length=200), nullable=False),
    sa.Column('company_address_2', sa.String(length=200), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('product_category', sa.String(length=255), nullable=True),
    sa.Column('product_sub_category', sa.String(length=255), nullable=True),
    sa.Column('vat', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('company_email'),
    sa.UniqueConstraint('company_name')
    )
    op.create_table('package_modes',
    sa.Column('package_mode_id', sa.Integer(), nullable=False),
    sa.Column('package_mode', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('package_mode_id'),
    sa.UniqueConstraint('package_mode')
    )
    op.create_table('product_categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('product_category', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('product_category')
    )
    op.create_table('product_sub_categories',
    sa.Column('sub_category_id', sa.Integer(), nullable=False),
    sa.Column('product_sub_category', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('sub_category_id'),
    sa.UniqueConstraint('product_sub_category')
    )
    op.create_table('shops',
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('shop_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('shop_id'),
    sa.UniqueConstraint('shop_name')
    )
    op.create_table('stores',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('store_id'),
    sa.UniqueConstraint('store_name')
    )
    op.create_table('shelves',
    sa.Column('shelf_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('shelf_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('shelf_id'),
    sa.UniqueConstraint('shelf_name')
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('product_description', sa.String(length=255), nullable=True),
    sa.Column('part_number', sa.String(length=50), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('buying_price', sa.Float(), nullable=False),
    sa.Column('wholesale_price', sa.Float(), nullable=False),
    sa.Column('retail_price', sa.Float(), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=False),
    sa.Column('product_category_id', sa.Integer(), nullable=False),
    sa.Column('product_sub_category_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('shelf_id', sa.Integer(), nullable=True),
    sa.Column('package_mode_id', sa.Integer(), nullable=True),
    sa.Column('shelf_names', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('shop_quantity', sa.Integer(), nullable=False),
    sa.Column('store_quantity', sa.Integer(), nullable=False),
    sa.Column('component', sa.Boolean(), nullable=True),
    sa.Column('hot_list', sa.Boolean(), nullable=True),
    sa.Column('dormant', sa.Boolean(), nullable=True),
    sa.Column('apply_vat', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['package_mode_id'], ['package_modes.package_mode_id'], ),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_categories.category_id'], ),
    sa.ForeignKeyConstraint(['product_sub_category_id'], ['product_sub_categories.sub_category_id'], ),
    sa.ForeignKeyConstraint(['shelf_id'], ['shelves.shelf_id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.shop_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('product_name')
    )
    op.create_table('product_conversion',
    sa.Column('conversion_id', sa.Integer(), nullable=False),
    sa.Column('from_product_id', sa.Integer(), nullable=False),
    sa.Column('to_product_id', sa.Integer(), nullable=False),
    sa.Column('unit_before', sa.String(length=50), nullable=False),
    sa.Column('conversion_quantity', sa.Float(), nullable=False),
    sa.Column('unit_after', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['to_product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('conversion_id')
    )
    op.create_table('product_transfer',
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('transfer_quantity', sa.Float(), nullable=False),
    sa.Column('from_location', sa.String(length=100), nullable=False),
    sa.Column('to_location', sa.String(length=100), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('transfer_id')
    )
    op.create_table('write_off',
    sa.Column('write_off_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('write_off_quantity', sa.Float(), nullable=False),
    sa.Column('buying_price', sa.Float(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('write_off_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('write_off')
    op.drop_table('product_transfer')
    op.drop_table('product_conversion')
    op.drop_table('products')
    op.drop_table('shelves')
    op.drop_table('stores')
    op.drop_table('shops')
    op.drop_table('product_sub_categories')
    op.drop_table('product_categories')
    op.drop_table('package_modes')
    op.drop_table('companies')
    # ### end Alembic commands ###
